# Generated by Django 4.2.5 on 2023-09-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('kingdom', models.CharField(max_length=30)),
                ('pyhlum', models.CharField(max_length=30)),
                ('_class', models.CharField(max_length=30)),
                ('superfamily', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='animal name')),
                ('image', models.URLField(verbose_name='animal image')),
                ('age', models.IntegerField(default=0, verbose_name='animal age')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.metadata')),
            ],
        ),
    ]
